### PR TITLE
comment

### PR DESCRIPTION
**Pull request by vedtam**

### CODE REVIEW

**Comment by theodorDiaconu** [comment]
Hi, not a typo. Sometimes it's better to use it without .js, because you can later create a folder with index.js in it, without altering the code. Let's you modularize it further more.

**Comment by vedtam** [comment]
Sorry, yes I have realized along the way. I than have updated my pull request to add the comment the same way you did in the next lesson:

https://github.com/cult-of-coders/meteor-tuts/pull/1/commits/7a208f5b4fc9f3972c951771935aaacf1d14eb40

**Comment by theodorDiaconu** [comment]
Yes, but your point was very valid. If someone is new! It creates confusion by bombarding him with "so many ways to do things". This is why I think it's better to keep it simple and use ".js" ?

**Comment by vedtam** [comment]
not necessarily, you can keep it that way (without .js), you may only  include the comment: `// no .js ? yep, works like that too!`\- like in the next lesson.

**Comment by vedtam** [comment]
By the way. Are you on some irc / slack channel (#meteor, #node, #startup)? Maybe sometime we could come together for a little chatting about node/js in general :)

**Comment by theodorDiaconu** [comment]
my name is fatninja @ freenode I stay on #meteor

**Comment by vedtam** [comment]
Cool, thanks!

**Pull request closed without merging**
